apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-ingress
  namespace: my-anvil-tutorial
spec:
  ingressClassName: nginx
  rules:
    - host: dane.anvilcloud.rcac.purdue.edu
      http:
        paths:
          # API calls go to backend (must be first for priority)
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: fastapi-svc
                port:
                  number: 8080
          # Everything else goes to frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 3000
